import Head from "next/head";
import { supabase } from "../../utils/supabase";
import Link from "next/link";
import { useUser } from "../../context/user";

export default function CompaniesPage({ companies }) {
  const { user } = useUser();

  const pic = process.env.NEXT_PUBLIC_BUCKET_URL;

  return (
    <div className="">
      <Head>
        <title>Remote companies</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" min-h-screen">
        <section className=" flex justify-center w-full ">
          <div className="grid grid-cols-4 gap-4 max-w-7xl my-12 ">
            <div className="flex flex-col justify-center col-span-3 max-w-4xl ">
              <h1 className="text-6xl sm:text-8xl font-black mb-6">
                Grow the people of tomorrow
              </h1>
              <p className="text-xl">
                Find juniors eager to learn. Offer them placement in your
                company and watch them grow.
              </p>
              <p className="text-blue-500 mt-6">
                Remotecompanies helps you find a placement in companies that
                value learning. Create a profile and expose yourself to hands-on
                work in the new era of remote.
              </p>
            </div>
            <div className="w-full ">
              <img src="/banner.png" />
            </div>
          </div>
        </section>
        {companies.length < 2 ? (
          <p>{companies.length} company available</p>
        ) : (
          <p>{companies.length} companies available</p>
        )}
        <section className="grid sm:grid-cols-4 gap-2 text-yellow-50">
          {companies ? (
            companies.map((company) => (
              <Link key={company.id} href={`/profile/${company.id}`}>
                <a className="border border-gray-700 rounded-xl p-3">
                  <img
                    src={`${pic}${company.avatar_url}`}
                    className="rounded-full w-32"
                  />
                  <p>{company.name}</p>
                  <p>{company.location}</p>
                  <p className="text-sm">{company.motivation}</p>
                </a>
              </Link>
            ))
          ) : (
            <p>"No companies to display yet"</p>
          )}
        </section>
      </main>
    </div>
  );
}
export const getStaticProps = async () => {
  const { data: companies } = await supabase.from("companies").select("*");
  return {
    props: {
      companies,
    },
  };
};
