import Head from "next/head";
import { supabase } from "../utils/supabase";
import Link from "next/link";
import { useUser } from "./context/user";

export default function Home({ juniors }) {
  const { user } = useUser();

  return (
    <div className="">
      <Head>
        <title>Remote Juniors</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" min-h-screen">
        <div className="flex gap-2 text-blue-500">
          {juniors &&
            juniors.map((junior) => (
              <Link key={junior.id} href={`${junior.id}`}>
                <a>
                  {junior.firstName} {junior.lastName}
                </a>
              </Link>
            ))}
        </div>
      </main>
    </div>
  );
}

export const getStaticProps = async () => {
  const { data: juniors } = await supabase.from("profiles").select("*");
  return {
    props: {
      juniors,
    },
  };
};
